server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eban?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      # ????
      pool-name: DateHikariCP
      # ???????
      minimum-idle: 5
      # ??????????(???6*10^5,10??)
      idle-timeout: 180000
      # ?????
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ????????(0:????;???1.8*10^6,30??)
      max-lifetime: 1800000
      # ??????(???30000,3??)
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1

# mybatis-plus??
mybatis-plus:
  # mapper????
  mapper-location: classpath*:/mapper/*Mapper.xml
  # mybatis?????????
  type-aliases-package: cn.iris.server.pojo
  configuration:
    # ??????
    map-underscore-to-camel-case: false

# Mybatis SQL??(????????,??Mapper.xml????)
logging:
  level:
    cn.iris.server.mapper: debug