server:
  port: 8082
spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: MSAMUFNULBYRWPAW
    username: supiris@163.com
    port: 25
  # rabbitmq配置
  rabbitmq:
    username: iris
    password: foxiris@qq.com
    host: 192.168.47.102
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    # 超时时间：10000ms
    timeout: 10000ms
    # Redis服务器地址
    host: 192.168.47.102
    port: 6379
    # 指定数据库
    database: 0
    # 密码
    password: foxiris@qq.com
    lettuce:
      pool:
        # 最大连接数（默认为8）
        max-active: 1024
        # 最大连接阻塞等待时间（默认-1，一直等）
        max-wait: 10000ms
        # 最大空闲连接数
        max-idle: 200
        # 最小空闲连接数
        min-idle: 5